CREATE TABLE  "AFTER_ASH" 
   (	"AFTER_ASH_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"HEALING_DOG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"AFTER_ASH_TITLE" VARCHAR2(200), 
	"AFTER_ASH_CONTENT" VARCHAR2(4000), 
	"AFTER_ASH_DATE" VARCHAR2(30), 
	"AFTER_ASH_TIME" VARCHAR2(20), 
	"AFTER_ASH_VEDIO" VARCHAR2(300), 
	"AFTER_ASH_IMAGE" VARCHAR2(300), 
	"AFTER_ASH_VIEW_COUNT" VARCHAR2(10) DEFAULT '0', 
	"REG_DATE" DATE, 
	"DELETE_FLAG" VARCHAR2(3) DEFAULT 0, 
	 PRIMARY KEY ("AFTER_ASH_NO") ENABLE, 
	 UNIQUE ("AFTER_ASH_VEDIO") ENABLE, 
	 UNIQUE ("AFTER_ASH_IMAGE") ENABLE, 
	 FOREIGN KEY ("HEALING_DOG_NO")
	  REFERENCES  "HEALING_DOG" ("HEALING_DOG_NO") ENABLE
   )