CREATE TABLE  "ASH_RESERVATION" 
   (	"ASH_RESERVATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"HEALING_DOG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ASH_RESERVATION_NAME" VARCHAR2(20), 
	"ASH_RESERVATION_DATE" VARCHAR2(30), 
	"ASH_RESERVATION_TIME" VARCHAR2(20), 
	"ASH_RESERVATION_ADDRESS1" VARCHAR2(200), 
	"ASH_RESERVATION_ADDRESS2" VARCHAR2(200), 
	"ASH_RESERVATION_PHONE" VARCHAR2(20), 
	"ASH_RESERVATION_PRICE" NUMBER(20,0), 
	"ASH_RESERVATION_ETC" VARCHAR2(200), 
	"ASH_RESERVATION_CONDITION" VARCHAR2(3) DEFAULT 0, 
	"PURCHASE_DATE" DATE, 
	"PAYMENT_OPTION" VARCHAR2(3) DEFAULT 0, 
	 PRIMARY KEY ("ASH_RESERVATION_NO") ENABLE, 
	 FOREIGN KEY ("HEALING_DOG_NO")
	  REFERENCES  "HEALING_DOG" ("HEALING_DOG_NO") ENABLE
   )