CREATE TABLE  "CART" 
   (	"CART_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PROD_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"CART_QUANTITY" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("CART_NO") ENABLE, 
	 FOREIGN KEY ("PROD_NO")
	  REFERENCES  "PRODUCT" ("PROD_NO") ENABLE
   )