CREATE TABLE  "DOG_INFO" 
   (	"DOG_INFO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"DOG_INFO_IMAGE" VARCHAR2(300), 
	"DOG_INFO_CONTENT" VARCHAR2(1000), 
	"DOG_INFO_TITLE" VARCHAR2(200) NOT NULL ENABLE, 
	"DOG_INFO_TOPIC" VARCHAR2(20), 
	"DOG_INFO_VIEW_COUNT" VARCHAR2(10) DEFAULT '0', 
	"DOG_INFO_RECOMMEND" VARCHAR2(10) DEFAULT '0', 
	"DOG_INFO_NOT_RECOMMEND" VARCHAR2(10) DEFAULT '0', 
	"REG_DATE" DATE, 
	"DELETE_FLAG" VARCHAR2(3) DEFAULT '0', 
	 PRIMARY KEY ("DOG_INFO_NO") ENABLE, 
	 UNIQUE ("DOG_INFO_IMAGE") ENABLE
   )