CREATE TABLE  "PRODUCT" 
   (	"PROD_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROD_TYPE" VARCHAR2(3), 
	"PROD_NAME" VARCHAR2(100), 
	"PROD_IMAGE" VARCHAR2(300), 
	"PROD_CONTENT" VARCHAR2(100), 
	"REG_DATE" DATE, 
	"PROD_QUANTITY" NUMBER(5,0), 
	"PRICE" NUMBER(10,0), 
	"DELETE_FLAG" VARCHAR2(3) DEFAULT '0', 
	 PRIMARY KEY ("PROD_NO") ENABLE, 
	 UNIQUE ("PROD_IMAGE") ENABLE
   )