CREATE TABLE  "REVIEW" 
   (	"PURCHASE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROD_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"REVIEW_TITLE" VARCHAR2(100), 
	"REVIEW_CONTENT" VARCHAR2(300), 
	"REVIEW_SCORE" NUMBER(1,0) NOT NULL ENABLE, 
	"REG_DATE" DATE, 
	"DELETE_FLAG" VARCHAR2(3) DEFAULT '0', 
	 PRIMARY KEY ("PURCHASE_NO") ENABLE, 
	 FOREIGN KEY ("PROD_NO")
	  REFERENCES  "PRODUCT" ("PROD_NO") ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
   )